
apiVersion: v1
kind: Pod
metadata:
  name: java-nodeapp
  labels:
    app: java-nodeapp
spec:
  containers:
    - name: java-nodeapp
      image: raouagara/java-nodeapp:tagVersion
      ports:
        - containerPort: 8080
