---
apiVersion: v1
kind: Pod
metadata:
  name: java-nodeapp
  labels:
    app: java-nodeapp
spec:
  containers:
    - name: nodeapp
      image: raouagara/java-nodeapp:latest
      ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: java-nodeapp
spec:
  selector:
    app: java-nodeapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer   
---
  
