--- 
apiVersion: apps/v1
kind: Pod
metadata: 
  labels: 
    app: java-nodeapp
  name: java-nodeapp
spec: 
  containers: 
    - 
      image: "raouagara/java-nodeapp:tagVersion"
      name: java-nodeapp
      ports: 
        - 
          containerPort: 8080
